In [1]:
import numpy as np

In [2]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [3]:
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [5]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(1,11).reshape(2,5) # converting into 2 x 5 matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
#ones and zeros

In [14]:
np.ones((3,4)) # put inside brackets

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.random.rand(3,4)

array([[0.1882094 , 0.02413233, 0.20593585, 0.8402829 ],
       [0.70353865, 0.77202144, 0.38331476, 0.91319813],
       [0.85646416, 0.2587173 , 0.20079591, 0.16363052]])

In [17]:
# numpy has fixed size and are homogenous - meaning data of same type only

In [18]:
arr = np.arange(10)

In [19]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr = np.append(arr, [10,20])

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 20])

In [24]:
arr = np.append(arr, ['A',20]) # acceptable but all get converted into string

In [25]:
arr

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '20', 'A',
       '20', 'A', '20'], dtype='<U21')

In [26]:
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr2 = np.append(arr2, [10.3]) # all elements gets converted in to float

In [30]:
arr2

array([ 0. ,  1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 10.3,
       10.3])

In [ ]:
np.random.rand(2,5) # matrix 2x5 with values between 0 and 1

array([[0.87035386, 0.30209726, 0.63801089, 0.19016788, 0.79329974],
       [0.04980861, 0.79851661, 0.59058062, 0.96901723, 0.42628055]])

In [ ]:
# linespace
