In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
import sys

In [4]:
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:11:29) [Clang 20.1.8 ]'

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [8]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [11]:
np.arange(20,10) # no error but first element should be larger than the second element.

array([], dtype=int64)

In [12]:
np.arange(-10,10)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [13]:
np.arange(-5,0)

array([-5, -4, -3, -2, -1])

In [14]:
np.arange(-5,1)

array([-5, -4, -3, -2, -1,  0])

In [ ]:
np.arange() # requires atleast one argument.

TypeError: arange() requires stop to be specified.

In [17]:
np.arange(10,20,2) # with step of 2

array([10, 12, 14, 16, 18])

In [18]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [ ]:
np.arange(1,2,3,4) # max 4 args allowed

TypeError: Cannot interpret '4' as a data type

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [23]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [24]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [25]:
np.zeros((5,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [26]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [28]:
np.ones((5,7), dtype=int) # 5 rows and 7 cols

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [ ]:
np.random.rand(5)

array([0.66166888, 0.50170545, 0.36456841, 0.21215361, 0.15829126])

In [44]:
np.random.rand(5) # array of 5 elements between 0 and 1


array([0.52700771, 0.34652147, 0.49671916, 0.21971085, 0.26195034])

In [45]:
np.random.rand(3,4)

array([[0.02220009, 0.58082477, 0.47317334, 0.83830535],
       [0.94749248, 0.9017351 , 0.47585497, 0.063954  ],
       [0.88873981, 0.91594471, 0.43249707, 0.3216691 ]])

In [81]:
np.random.rand(3,4)


array([[0.69643355, 0.17034241, 0.74681762, 0.16851144],
       [0.35997577, 0.87382735, 0.12633005, 0.13121355],
       [0.4502383 , 0.14104624, 0.42519166, 0.11280163]])

In [84]:
np.random.rand(3,5,2)

array([[[0.72747036, 0.60319432],
        [0.86964537, 0.09553021],
        [0.15113846, 0.22764895],
        [0.07786999, 0.48913563],
        [0.15928646, 0.65852201]],

       [[0.13000483, 0.05603971],
        [0.23333984, 0.91653572],
        [0.33836895, 0.07820264],
        [0.38454912, 0.17846868],
        [0.82616622, 0.5570874 ]],

       [[0.81633048, 0.80082949],
        [0.52504899, 0.9962735 ],
        [0.35462087, 0.3943981 ],
        [0.54292461, 0.64352865],
        [0.17096151, 0.18621785]]])

In [86]:
np.random.rand(3,5,2,2, 4)


array([[[[[0.69108826, 0.44929885, 0.59322064, 0.43312912],
          [0.59863262, 0.18287761, 0.65504003, 0.97795179]],

         [[0.58625895, 0.43844156, 0.32892996, 0.67555083],
          [0.62362436, 0.83416943, 0.33649888, 0.14826625]]],


        [[[0.21130211, 0.50112332, 0.1855109 , 0.80272446],
          [0.54927143, 0.71124323, 0.48157574, 0.56256586]],

         [[0.24472428, 0.39543091, 0.5583271 , 0.88726364],
          [0.87083719, 0.63056603, 0.21791549, 0.32894418]]],


        [[[0.19291642, 0.27392777, 0.03451871, 0.44837757],
          [0.74952639, 0.7017651 , 0.51734663, 0.1700265 ]],

         [[0.61930516, 0.42887618, 0.85491155, 0.59862718],
          [0.36990848, 0.44065516, 0.26620273, 0.04367283]]],


        [[[0.85176249, 0.45404411, 0.8514483 , 0.55077903],
          [0.37054165, 0.76950685, 0.90704758, 0.81521387]],

         [[0.38980093, 0.72549067, 0.35612197, 0.95091072],
          [0.60404116, 0.34576329, 0.97403264, 0.11388386]]],


        [[[0.199

In [87]:
np.random.rand(10,20,5)

array([[[2.44890414e-02, 9.98384355e-01, 2.08498336e-01, 3.01668562e-01,
         4.56890155e-01],
        [6.97461484e-01, 6.28835902e-01, 1.72406444e-01, 2.40124666e-01,
         6.68064303e-01],
        [3.43333887e-01, 8.84035629e-01, 9.14085385e-01, 7.30201261e-01,
         9.28875473e-01],
        [7.43470844e-01, 8.70917458e-01, 5.08264669e-01, 9.54773704e-01,
         3.52363179e-01],
        [8.56600866e-01, 3.53977231e-01, 6.21226429e-02, 1.73490672e-01,
         2.82930524e-01],
        [4.52315805e-01, 5.56907642e-01, 9.70603094e-01, 5.25272155e-01,
         6.41211751e-01],
        [7.72247199e-01, 3.75474254e-01, 3.34600522e-01, 6.48330074e-01,
         4.20977639e-01],
        [8.64203804e-01, 9.00495226e-01, 9.14546989e-01, 9.11753695e-01,
         3.58032084e-01],
        [2.52019324e-01, 6.77016899e-01, 5.92792819e-01, 5.11493207e-01,
         9.63541141e-01],
        [5.52455505e-01, 1.96595056e-01, 3.04006633e-01, 5.26693271e-01,
         4.79111581e-01],
        [9

In [2]:
import numpy as np
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [18]:
np.random.randint(3,10)

9